services:
  dvwa:
    image: vulnerables/web-dvwa
    platform: linux/amd64
    container_name: dvwa
    ports:
      - "8080:80"

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
